### ISSUE TITLE
Pkg.test() on windows with Julia-0.5 fails

### ISSUE THREAD

**Issue by mdpradeep** [stevengj/DecFP.jl#32] opened 2016-10-04 10:17 UTC
```
julia> Pkg.test("DecFP")
INFO: Testing DecFP
TESTING DecFP.Dec32 ...
Test Failed
  Expression: @d32_str("3.2") * @d32_str("4.5") == @d32_str("14.4")
   Evaluated: +4619304E-100 == +4619304E-100
ERROR: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Fail) at .\test.jl:397
 in do_test(::Base.Test.Returned, ::Expr) at .\test.jl:281
 in macro expansion; at C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0.5.0
.1\v0.5\DecFP\test\runtests.jl:13 [inlined]
 in anonymous at .\<missing>:?
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0.5.0.1\v0.5\De
cFP\test\runtests.jl, in expression starting on line 9
================================[ ERROR: DecFP ]================================


failed process: Process(`'C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\Julia-0.
5.0\bin\julia' -Cx86-64 '-JC:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\Julia-0
.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-co
verage=none --color=yes --compilecache=yes 'C:\Users\julia\AppData\Local\JuliaPr
o-0.5.0.1\pkgs-0.5.0.1\v0.5\DecFP\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

ERROR: DecFP had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:74
0
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array
{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstract
String,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstra
ctString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::V
ararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::A
rray{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:25
8
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
```

**Comment by quinnj** [comment] 2016-10-04 17:04
DecFP has never worked on Windows as far as I know, we should probably put this front and center in the README so people don't try to use the package on windows, at least until https://github.com/JuliaLang/METADATA.jl/pull/6626 can make progress

**Comment by jebej** [comment] 2017-01-13 13:36
DecFP is still broken on Windows, any progress on the issue?

**Comment by stevengj** [comment] 2017-01-13 18:26
Duplicate of #10.

**Closed by stevengj** 2017-01-13 18:26 UTC
