### ISSUE TITLE
sqrt on Dec32 is painfully slow and allocates

### ISSUE THREAD

**Issue by mohamed82008** [stevengj/DecFP.jl#58] opened 2018-02-10 02:39 UTC
```julia
julia> using DecFP

julia> af = rand(Float32);

julia> ad = Dec32(af);

julia> using BenchmarkTools

julia> @btime sqrt($af)
  1.093 ns (0 allocations: 0 bytes)
0.8627168f0

julia> @btime sqrt($ad)
  5.531 μs (15 allocations: 720 bytes)
0.862717
```
Interestingly, raising to power 0.5 is much faster and does not allocate:
```julia
julia> exf = Float32(0.5); exd = Dec32(0.5);

julia> @btime ($af)^($exf)
  6.564 ns (0 allocations: 0 bytes)
0.8627168f0

julia> @btime ($ad)^($exd)
  117.763 ns (0 allocations: 0 bytes)
0.862717
```

**Comment by stevengj** [comment] 2018-02-14 19:05
The problem is the `xchk` function in DecFP, which checks for an error, and takes the error string as a parameter.  Doing it this way was a mistake, because it means that the error message is allocated even if no error is detected.

It really needs to be rewritten, e.g. as a macro.

**Comment by quinnj** [comment] 2018-02-15 03:45
Another way to do this is have a separate function that throws w/ `@noinline`, like
```julia
@noinline thrower() = throw(ArgumentError("you did something bad"))
function foo()
    # do stuff
    valid || thrower()
end
```
You could obviously pass some arguments to `thrower` to make the error message more meaningful.

**Comment by stevengj** [comment] 2018-03-01 16:38
Should be fixed now.

**Closed** 2018-03-01 16:38 UTC
Labels: enhancement
